version: "3.8"

services:
  api:
    build: .
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - db
    ports:
      - 5000:5000


  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/veloto.conf:/etc/nginx/conf.d/veloto.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /veloto/srv/certs:/veloto/srv/certs
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
