version: "3.8"

services:
#  api:
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#    expose:
#      - 8000
#    command: /bin/bash -c "aft/app.py"


  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

